
if(NOT DEFINED NAME OR NOT DEFINED DLL OR NOT DEFINED OUTPUT)
    message(FATAL_ERROR "write-plugin-manifest.cmake: NAME, DLL and OUTPUT are required")
endif()
if(NOT EXISTS "${DLL}")
    message(FATAL_ERROR "write-plugin-manifest.cmake: dll not found: ${DLL}")
endif()

string(TIMESTAMP COMPILED_AT "%Y-%m-%dT%H:%M:%SZ" UTC)
file(SHA256 "${DLL}" DLL_SHA256)

set(LINES "  \"name\": \"${NAME}\"")
if(DEFINED VERSION AND NOT VERSION STREQUAL "")
    list(APPEND LINES "  \"version\": ${VERSION}")
endif()
list(APPEND LINES "  \"compiled_at\": \"${COMPILED_AT}\"")
list(APPEND LINES "  \"sha256\": \"${DLL_SHA256}\"")
if(DEFINED DISPLAY_VERSION AND NOT DISPLAY_VERSION STREQUAL "")
    list(APPEND LINES "  \"display_version\": \"${DISPLAY_VERSION}\"")
endif()
if(DEFINED ABI AND NOT ABI STREQUAL "")
    list(APPEND LINES "  \"toolbox_abi\": ${ABI}")
endif()
if(DEFINED BUILD_ID AND NOT BUILD_ID STREQUAL "")
    list(APPEND LINES "  \"build_id\": \"${BUILD_ID}\"")
endif()
list(JOIN LINES ",\n" BODY)

file(WRITE "${OUTPUT}" "{\n${BODY}\n}\n")
