execute_process(COMMAND git -c safe.directory=${PROJECT_SOURCE_DIR} rev-parse --short=12 HEAD
    WORKING_DIRECTORY "${PROJECT_SOURCE_DIR}" OUTPUT_VARIABLE GWTOOLBOX_FORK_BUILD_ID
    OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET)
if(NOT GWTOOLBOX_FORK_BUILD_ID)
    set(GWTOOLBOX_FORK_BUILD_ID "local")
endif()
set(GWTOOLBOX_FORK_VERSION 1)
set(DBBOX_PLUGIN_VERSION 1)
set(GWTOOLBOX_PLUGIN_ABI 1)
set(GWTOOLBOX_FORK_DISPLAY_VERSION "${GWTOOLBOXDLL_VERSION}.${GWTOOLBOX_FORK_VERSION}")
configure_file("${PROJECT_SOURCE_DIR}/cmake/ForkVersion.h.in"
    "${CMAKE_BINARY_DIR}/generated/ForkVersion.h" @ONLY)
include_directories("${CMAKE_BINARY_DIR}/generated")
